### ISSUE TITLE
Move to Github Actions

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-webui#1595]
We had success with moving to github actions in ipfs-desktop, we should do the same here.

## Side issue: CI tests do not run on PRs from forks

Right now testing and publishing release is handled by the same circleCI job, which is [limited to local branches](https://github.com/ipfs-shipyard/ipfs-webui/blob/07571b5424537527ca8e3e41e1ed3c8d2bdbf81f/.circleci/config.yml#L58-L69). 
This means the current setup does not run tests on PRs submitted by community, such as https://github.com/ipfs-shipyard/ipfs-webui/pull/1572

##  TODO 

- [ ] add GitHub Action which builds and runs all tests on every `push, pull_request`
- [ ] (optional) switch publishing or switch to https://github.com/ipfs-shipyard/ipfs-github-action
- [ ] Keep CircleCI to detect if tests timeout there – go-ipfs is still running our E2E on CircleCI, so we need to keep it green (ok to run it only on master and non-fork PRs)
- [ ] attach CAR file to release, so people can import it when in private swarms with more confidence(https://github.com/ipfs-shipyard/ipfs-webui/issues/1727)
    ```console
    $ ipfs dag export bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i > webui_v2.11.4.car
    $ ipfs dag import webui_v2.11.4.car
    Pinned root	bafybeif4zkmu7qdhkpf3pnhwxipylqleof7rl6ojbe7mq3fzogz6m4xk3i	success
    ```
