### ISSUE TITLE
WebUI can't connect to running IPFS Desktop node using http://webui.ipfs.io.ipns.localhost:8080/#/welcome

### ISSUE THREAD

**Issue by momack2** [ipfs/ipfs-webui#1880]
**Describe the bug**
when visiting http://webui.ipfs.io with a local IPFS Desktop node running, I get an error that it could not connect to the IPFS API -- however loading the webUI from http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/ works fine.

**To Reproduce**
1. Run local IPFS desktop node
2. Go to http://webui.ipfs.io
3. See error
4. Go to http://127.0.0.1:5001/ipfs/bafybeihcyruaeza7uyjd6ugicbcrqumejf6uf353e5etdkhotqffwtguva/#/ or click "status" in IPFS Desktop menu - see correctly behaving node

**Expected behavior**
http://webui.ipfs.io should correctly connect to the IPFS node API

**Screenshots**
![image](https://user-images.githubusercontent.com/618519/147889237-6337f46b-8979-4098-97f9-7c8a3037d0d3.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by hacdias** [comment]
Hey @momack2! Quick question: did it work before and nothing changed? Perhaps a new installation/computer/user/IPFS repo. I can reproduce your error, but running the commands on step 2) fixes it.

Note: the Web UI at 127.0.0.1:5001 will work because it is in the same domain as the API. The version in https://webui.ipfs.io requires the correct CORS headers to be set.

@lidel I'm aware some things regarding CORS and IPFS changed lately (cc https://github.com/ipfs/ipfs-desktop/pull/1899#issuecomment-996707925). Can you take a look?

**Idea**: add an option in IPFS Desktop's menu to execute the commands in step 2). Some users may be uncomfortable with using a CLI and that would provide an alternative. What do you think?

**Comment by momack2** [comment]
Gotcha - that was my hypothesis, but because I'm not actually running an IPFS node from the terminal (I'm running it via IPFS Desktop) I don't have a clear place to run those commands (I'm not sure where my ipfs directory is, or how to get at my running IPFS daemon inside Desktop). Maybe that is some documentation we can add to this error message, or to the settings page to help resolve for new users?

**Comment by lidel** [comment]
Agree with @momack2 suggestion that the CLI step should not be necessary for Desktop users, especially given adding `ipfs` CLI to `PATH` does not work reliably across all operating systems and distributions.  

IPFS Desktop should be safelisting webui.ipfs.io) in IPFS Desktop by default. 

### TODO here is

- [ ] change default `API.HTTPHeaders['Access-Control-Allow-Origin']` array to include `https://webui.ipfs.io` and `http://webui.ipfs.io.ipns.localhost:8080`
- [ ] migrate existing users: add above entries if missing (they may be missing `Access-Control-Allow-Origin` entierely)
- [ ] detect when Gateway port is different from  8080 and update CORS localhost entry before starting the daemon
  - caveat:  `Addresses.Gateway` can be a string or array of strings – we need to detect both cases and in case of an array pick the `127.0.0.1` one 

>  I'm aware some things regarding CORS and IPFS changed lately (cc ipfs/ipfs-desktop#1899 (comment)). Can you take a look?

CORS handling changed only in Electron context (we no longer need to manually tweak Origin). Here we talk about loading http://webui.ipfs.io  in regular browser while IPFS Desktop daemon is running, so it is not impacted.
