### ISSUE TITLE
MacOS app search filed is grayed out

### ISSUE THREAD

**Issue by yahorshumski** [ipfs/ipfs-webui#2245]
MacOS app search filed is grayed out

<img width="741" alt="image" src="https://github.com/user-attachments/assets/537308f4-7146-49d1-9ca2-64fa1d3c06ec">

```[tasklist]
### Tasks
- [ ] https://github.com/ipfs/ipfs-webui/pull/2211
- [ ] https://github.com/ipfs/ipfs-webui/pull/2197
- [ ] https://github.com/ipfs/ipfs-webui/issues/2244
- [ ] https://github.com/ipfs/ipfs-webui/pull/2220
- [ ] https://github.com/ipfs/ipfs-webui/pull/2215
- [ ] https://github.com/ipfs/ipfs-webui/issues/2234
- [ ] https://github.com/ipfs/ipfs-webui/pull/2168
```

**Comment by dannyob** [comment]
Hi -- I'm seeing the same thing here. version Version 0.44.0 (0.44.0), https://github.com/ipfs/ipfs-webui/commit/546d20a

<img width="1048" height="144" alt="Image" src="https://github.com/user-attachments/assets/a5106610-2737-4f33-98a6-9861a0653167" />

This is from clicking on an IPFS: URL in the browser -- Desktop will start, but the resource pointed to by the IPFS link will not load.
